# Generated by Django 2.0.5 on 2018-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180930_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvk', models.IntegerField()),
                ('relation', models.IntegerField()),
                ('lastRelation', models.IntegerField()),
                ('dateChange', models.DateTimeField(auto_now_add=True)),
                ('sex', models.IntegerField()),
                ('city', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('photourl', models.CharField(max_length=500)),
            ],
        ),
    ]
