# Generated by Django 2.1 on 2018-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_changedpeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedpeople',
            name='relation',
            field=models.CharField(max_length=100),
        ),
    ]
